### ISSUE TITLE
Permission to store icon theme in other repo

### ISSUE THREAD

**Issue by techcoder20** [yeyushengfan258/BigSur-icon-theme#4]
Hi @yeyushengfan258  I am the creator of [MacOSBigSurThemeConverter ](https://github.com/techcoder20/MacOSBigSurThemeConverter). I make use of your icon theme in my script and have credited you at every point possible. Currently in my script I clone your script and run the install script. Will it be fine with you if I store the icon theme in my repo ? The reason I prefer storing the themes in my repo is that it will reduce the time of installation. So I would really like it if you could give me permission to store the icon theme in my repo :)

**Comment by yeyushengfan258** [comment]
Of course, as long as the attribution source is fine, I'm glad to help you. And thank you for your support.

I'm sorry I just saw this email.

**Comment by techcoder20** [comment]
Thx 😁
