### ISSUE TITLE
Icon theme won't persist

### ISSUE THREAD

**Issue by krznv** [yeyushengfan258/BigSur-icon-theme#5]
So the theme works when I select it, but after restart it goes back to some broken Breeze style.

Any idea why they don't persist?

KDE Debian

Edit: I'm using your McSur-dark global theme and none of the icon packs work

**Comment by yeyushengfan258** [comment]
I don't understand that very well

**Comment by krznv** [comment]
Pardon me, you can remove the issue

It probably has nothing to do with your good work, must be something with my setup
